allow sensors dac_override
sensors needs dac_override, otherwise the folllowing logcat messages occur:

E/Sensors (  192): sns_debug_main.c(438):Debug Config File missing in EFS!
E/Sensors (  192): sns_smr_util.c(104):Unable to initialize service 259 with QCCI, timed out (2000 ms)
E/Sensors (  192): sns_acm_mr.c(388):Error getting info for service 3
E/Sensors (  192): sns_main.c(819):bind error 98
E/Sensors (  192): sns_main.c(819):bind error 98
D/SensorService(  752): nuSensorService starting...
I/qcom_sensors_hal(  752): hal_init: Setting log level to 4
E/qcom_sensors_hal(  752): hal_init: Error in sensor_reg_write(): -4
E/qcom_sensors_hal(  752): hal_check_ltcy_ssi_reg_flag: Error in sensor_reg_read() for reg flag: -4
E/qcom_sensors_hal(  752): hal_check_ltcy_ssi_reg_flag: Error in sensor_reg_read() for reg flag: -4
E/qcom_sensors_hal(  752): hal_check_ltcy_ssi_reg_flag: Error in sensor_reg_read() for reg flag: -4
E/qcom_sensors_hal(  752): hal_check_ltcy_ssi_reg_flag: Error in sensor_reg_read() for reg flag: -4
E/qcom_sensors_hal(  752): hal_check_ltcy_ssi_reg_flag: Error in sensor_reg_read() for reg flag: -4
E/qcom_sensors_hal(  752): _hal_sensors_get_sensors_list: sensor1 init failed
E/qcom_sensors_hal(  752): _hal_sensors_get_sensors_list: sensor1 init failed

One way this bug manifests itself is by breaking screen autorotation.

  PRE-CONDITION:
  - Auto-rotate screen should be enabled (Settings > Accessibility > Auto-rotate screen)

  STEPS TO REPRODUCE:
  1. Launch any of the apps(Chrome,Gmail, Keep..) > change the orientation to landscape mode

  OBSERVED RESULTS:
  - Auto rotate screen not functioning for landscape mode

  EXPECTED RESULTS:
  - Device should display landscape/portrait mode as per user selection when auto-rotate screen option is enabled

Change-Id: I85cabeb28ab9e28a729d3930bfc454522f2a42cf